import React, {useEffect,useState,useRef,useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {Headphones, Play, Pause, ArrowRight, Plus, BookOpen, Library, ChartNoAxesCombined, Settings, Check, RotateCcw, Volume2, ExternalLink, Download, Upload, ChevronRight, CircleHelp, X, LoaderCircle, Flag, CheckCircle2} from 'lucide-react';
import './style.css';
import SoundLab from './SoundLab';
import GeminiSettings from './GeminiSettings';

type Exercise={id:string;sourceId:string;kind:'speech'|'youtube';text:string;goal:string;prompt:string;options:string[];answer:number|null;explanation:string;meaning:string;pattern:string;quality:string;start:number;end:number;audioUrl?:string};
type Session={id:string;exerciseIds:string[];index:number;status:string;startedAt:string};
type Attempt={exerciseId:string;goal:string;at:string;correct:boolean|null;scored:boolean;helped:boolean;firstExposure:boolean;note:string;reflection:string;plays:number};
type Source={id:string;title:string;url:string;status:string;message:string;count:number};
type Skill={id:string;label:string;count:number;fresh:number;correct:number;state:string};
type AppState={sources:Source[];session:Session|null;active:{sourceId:string}|null;goals:Record<string,string>;summary:{attempts:Attempt[];skills:Skill[];due:number;days:number;total:number;baseline:{date:string;reviewDate:string;summary:string;observations:string[];note:string}};ai:{configured:boolean;model:string};recommendations:{id:string;title:string;url:string;reason:string;type:string;checkedAt:string;available:boolean}[];recommendationCheck:{status:string;attemptedAt:string}|null};
type Bundle={session:Session;exercises:Exercise[];attempts:Attempt[];events:{exerciseId:string;type:string}[]};
declare global {interface Window {YT:any;onYouTubeIframeAPIReady:()=>void}}

async function api<T=any>(path:string,data?:unknown):Promise<T>{
 const r=await fetch('/api'+path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});
 const v=await r.json(); if(!r.ok)throw new Error(typeof v.detail==='string'?v.detail:'요청을 처리하지 못했어요. 다시 시도해주세요.'); return v;
}
const fmt=(n:number)=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
const date=(s:string)=>new Date(s).toLocaleDateString('ko-KR',{month:'long',day:'numeric'});
let ytPromise:Promise<void>|null=null;
function loadYT(){return ytPromise??=new Promise<void>((resolve,reject)=>{
 if(window.YT?.Player){resolve();return;} window.onYouTubeIframeAPIReady=()=>resolve();
 const script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';script.onerror=()=>{ytPromise=null;reject(new Error('영상 플레이어를 불러오지 못했어요.'));};document.head.appendChild(script);
});}

function Player({exercise:e,onEvent}:{exercise:Exercise;onEvent:(type:string,value?:unknown)=>Promise<void>}){
 const audio=useRef<HTMLAudioElement>(null);const slot=useRef<HTMLDivElement>(null);const player=useRef<any>(null);const stopAt=useRef(e.end);const alive=useRef(true);
 const [ready,setReady]=useState(e.kind==='speech');const [playing,setPlaying]=useState(false);const [error,setError]=useState('');const [rate,setRate]=useState(1);const [voices,setVoices]=useState<SpeechSynthesisVoice[]>([]);
 const onEventRef=useRef(onEvent);onEventRef.current=onEvent;
 useEffect(()=>{
  alive.current=true;
  if(e.kind==='speech'){
   const load=()=>setVoices(window.speechSynthesis?.getVoices().filter(v=>v.lang.startsWith('en'))||[]);load();window.speechSynthesis?.addEventListener('voiceschanged',load);
   return()=>{alive.current=false;window.speechSynthesis?.cancel();window.speechSynthesis?.removeEventListener('voiceschanged',load);};
  }
  let cancelled=false;let timer:ReturnType<typeof setInterval>;
  loadYT().then(()=>{
   if(cancelled||!slot.current)return;
   const div=document.createElement('div');slot.current.replaceChildren(div);
   player.current=new window.YT.Player(div,{width:'100%',height:'100%',videoId:e.sourceId,playerVars:{origin:location.origin,playsinline:1,rel:0,cc_load_policy:0},events:{
    onReady:()=>{if(!cancelled){setReady(true);player.current.cueVideoById({videoId:e.sourceId,startSeconds:e.start,endSeconds:e.end});}},
    onStateChange:(ev:any)=>{if(cancelled)return;setPlaying(ev.data===1);if(ev.data===1)void onEventRef.current('played').catch(x=>setError(x.message));},
    onError:()=>{if(!cancelled)setError('이 영상은 여기서 재생되지 않아요. 원본에서 들을 수 있습니다.');}
   }});
   timer=setInterval(()=>{if(player.current?.getPlayerState?.()===1&&player.current.getCurrentTime()>=stopAt.current){player.current.pauseVideo();void onEventRef.current('ended');}},150);
  }).catch(x=>setError(x.message));
  return()=>{cancelled=true;alive.current=false;clearInterval(timer);player.current?.destroy();player.current=null;};
 },[e.id]);
 async function play(){
  setError('');
  if(playing){if(e.audioUrl)audio.current?.pause();else if(e.kind==='speech')window.speechSynthesis.cancel();else player.current?.pauseVideo();setPlaying(false);await onEvent('pause');return;}
  if(e.audioUrl){if(audio.current){audio.current.currentTime=0;audio.current.playbackRate=rate;await audio.current.play();}return;}
  if(e.kind==='speech'){
   if(!window.speechSynthesis||!voices.length){setError('영어 음성이 없습니다. Windows 언어 설정에서 영어 음성을 설치한 뒤 다시 열어주세요.');return;}
   window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(e.text);u.lang=voices[0].lang;u.voice=voices[0];u.rate=rate;
   u.onstart=()=>{if(alive.current){setPlaying(true);void onEvent('played').catch(x=>setError(x.message));}};
   u.onend=()=>{if(alive.current){setPlaying(false);void onEvent('ended');}};
   u.onerror=(x)=>{if(alive.current){setPlaying(false);if(x.error!=='interrupted'&&x.error!=='canceled')setError('음성 재생이 되지 않았어요. 다시 시도해주세요.');}};
   window.speechSynthesis.speak(u);
  }else if(ready){stopAt.current=e.end;player.current.loadVideoById({videoId:e.sourceId,startSeconds:e.start,endSeconds:e.end});player.current.setPlaybackRate(rate);}
 }
 return <div className={'player '+(e.kind==='speech'?'audio-player':'video-player')}>
  {e.audioUrl&&<audio ref={audio} src={e.audioUrl} onPlay={()=>{setPlaying(true);void onEvent('played').catch(x=>setError(x.message));}} onPause={()=>setPlaying(false)} onEnded={()=>{setPlaying(false);void onEvent('ended');}} onError={()=>setError('연습 음성을 불러오지 못했어요.')}/>} {e.kind==='youtube'?<div className="video-slot" ref={slot}/>:<div className={'soundscape '+(playing?'is-playing':'')} aria-hidden="true">{Array.from({length:37},(_,i)=><i key={i} style={{height:`${12+Math.abs(Math.sin(i*1.71))*57}px`,animationDelay:`${i*45}ms`}}/>)}</div>}
  <div className="player-controls"><button className="play-button" onClick={()=>void play().catch(x=>setError(x.message))} disabled={!ready}><span>{playing?<Pause size={19}/>:<Play size={19} fill="currentColor"/>}</span>{playing?'일시정지':'듣기'}</button>
   <select aria-label="재생 속도" value={rate} onChange={ev=>{const v=Number(ev.target.value);setRate(v);player.current?.setPlaybackRate?.(v);void onEvent(v<1?'slow':'rate',v);}}><option value={1}>1배속</option><option value={0.85}>0.85배속</option><option value={0.75}>0.75배속</option></select>
   <small>{e.kind==='speech'?'합성 음성 · 별도로 만든 연습 문장':`${fmt(e.start)} – ${fmt(e.end)}`}</small></div>
  {error&&<p className="inline-error" role="alert">{error}</p>}
  {e.kind==='youtube'&&<a className="text-link" href={`https://www.youtube.com/watch?v=${e.sourceId}&t=${Math.floor(e.start)}s`} target="_blank" rel="noreferrer" onClick={()=>void onEvent('external_listen')}>원본에서 듣기 <ExternalLink size={13}/></a>}
 </div>;
}

function App(){
 const [state,setState]=useState<AppState|null>(null);const [page,setPage]=useState('sound');const [bundle,setBundle]=useState<Bundle|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [url,setUrl]=useState('');const [toast,setToast]=useState('');
 const refresh=useCallback(async()=>{try{setState(await api<AppState>('/state'));}catch(x){setError((x as Error).message);}},[]);
 useEffect(()=>{void refresh();const t=setInterval(()=>void refresh(),6000);return()=>clearInterval(t);},[refresh]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t);}},[toast]);
 async function start(goal?:string){setBusy(true);setError('');try{const s=await api<Session>('/sessions',{goal});setBundle(await api<Bundle>('/sessions/'+s.id));setPage('practice');}catch(x){setError((x as Error).message);}finally{setBusy(false);}}
 async function add(ev:React.FormEvent){ev.preventDefault();if(!url.trim())return;setBusy(true);setError('');try{await api('/sources',{url});setUrl('');setPage('library');await refresh();setToast('영상 준비를 시작했어요. 기존 연습은 계속할 수 있어요.');}catch(x){setError((x as Error).message);}finally{setBusy(false);}}
 const nav=[['sound','소리 연습실',Headphones],['home','의미 이해 연습',Volume2],['library','내 영상',Library],['history','학습 기록',ChartNoAxesCombined],['baseline','나의 출발점',BookOpen],['settings','설정과 백업',Settings]] as const;
 const linkForm=<form className="link-form" onSubmit={add}><label htmlFor="video-url">새 영상으로 이어가기</label><div><input id="video-url" type="url" placeholder="YouTube 링크를 붙여넣으세요" value={url} onChange={e=>setUrl(e.target.value)} required/><button disabled={busy} aria-label="영상 추가">{busy?<LoaderCircle className="spin" size={20}/>:<Plus size={22}/>}</button></div><small>자막과 연습 구간은 자동으로 준비합니다.</small></form>;
 if(!state)return <main className="loading"><Headphones size={36}/><h1>듣는 노트를 열고 있어요</h1>{error?<><p>{error}</p><button onClick={()=>void refresh()}>다시 연결</button></>:<LoaderCircle className="spin"/>}</main>;
 const summary=state.summary;
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('home');}}><span className="brand-icon"><Headphones size={24}/></span><span>듣는 노트<small>나의 리스닝 연습장</small></span></a><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setError('');}}><Icon size={19}/>{label}{id==='home'&&state.session&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-note"><span className="little-line"/><p>익숙한 문장에서<br/>새로운 이해로.</p><small>짧게 듣고, 연결하고, 다시 만나기</small></div><div className="local-mark"><i/> 이 컴퓨터에 학습 기록 저장</div></aside>
 <main className="workspace"><header className="topbar"><span>{page==='practice'?'집중 연습':nav.find(n=>n[0]===page)?.[1]}</span><span className="top-date">{new Date().toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'short'})}</span></header>
 {error&&<div className="error-banner" role="alert">{error}<button aria-label="닫기" onClick={()=>setError('')}><X size={17}/></button></div>}
 {page==='settings'&&<GeminiSettings/>}
 {page==='sound'&&<SoundLab sources={state.sources} activeSource={state.active?.sourceId} ai={state.ai.configured}/>}
 {page==='home'&&<div className="home-grid"><div className="main-column"><div className="page-heading"><h1>오늘도, 한 문장씩.</h1><p>들리는 단어를 넘어 설명의 의미를 연결해 보세요.</p></div><section className="today-panel"><div><span className="session-label"><Volume2 size={17}/> 오늘의 집중 연습</span><h2>실패했을까,<br/>실패하지 않았을까?</h2><p>긍정과 부정을 듣고,<br/>조건이 붙은 설명까지 이어갑니다.</p><button className="white-button" disabled={busy} onClick={()=>void start()}>{state.session?'이어서 연습하기':'오늘 연습 시작'}<ArrowRight size={19}/></button><small>약 5–10분 · 짧은 문장과 실제 영상</small></div><div className="listening-art" aria-hidden="true"><div className="art-orbit"/><div className="art-disc"><Headphones size={80} strokeWidth={1}/></div><div className="art-bars">{[18,32,54,28,65,43,20].map((h,i)=><i key={i} style={{height:h}}/>)}</div></div></section>
 <section className="path-section"><div className="section-heading"><h2>이렇게 연습해요</h2><span>도움은 필요한 만큼만</span></div><div className="learning-path">{[['듣고 이해하기','처음 들린 의미를 골라요'],['놓친 부분 연결하기','소리와 문구를 확인해요'],['새 문장에 적용하기','다른 내용으로 다시 들어요']].map(([h,p],i)=><div key={h}><span className="step-number">{i+1}</span><h3>{h}</h3><p>{p}</p></div>)}</div></section>
 <section className="video-section"><div className="section-heading"><h2>함께 듣는 영상</h2><button className="plain-button" onClick={()=>setPage('library')}>모두 보기 <ChevronRight size={16}/></button></div>{state.sources.slice(0,2).map(s=><SourceRow key={s.id} source={s} active={state.active?.sourceId===s.id} onSelect={async()=>{await api('/sources/'+s.id+'/select',{});await start();}}/>)}{linkForm}</section></div>
 <aside className="right-column"><div className="focus-note"><span className="note-corner"/><h2>지금 이어갈 목표</h2><p>작은 부정어를 놓쳐도<br/>뜻은 크게 달라지니까.</p><div className="goal-list">{summary.skills.slice(0,3).map(s=><button key={s.id} onClick={()=>void start(s.id)}><span><b>{s.label}</b><small>{s.state}</small></span><ChevronRight size={16}/></button>)}</div></div><section className="quiet-panel"><div className="section-heading"><h2>쌓이는 학습</h2><BookOpen size={18}/></div>{summary.total?<><p className="big-number">{summary.total}<span>개의 응답</span></p><p>{summary.days}일에 걸쳐 연습했어요.<br/>복습할 항목 {summary.due}개가 있어요.</p></>:<><p>아직 첫 연습 전이에요.</p><p className="muted">정답뿐 아니라 어떤 도움이 효과가 있었는지도 기록합니다.</p></>}<button className="text-link" onClick={()=>setPage('history')}>학습 기록 살펴보기 <ArrowRight size={15}/></button></section><div className="baseline-teaser"><span>9월 19일의 출발점</span><p>글로 아는 표현을<br/>소리에서도 알아듣기.</p><button className="plain-button" onClick={()=>setPage('baseline')}>처음 기록 보기 <ChevronRight size={15}/></button></div></aside></div>}
 {page==='practice'&&bundle&&<Practice key={bundle.session.id} initial={bundle} onDone={async()=>{await refresh();setPage('history');}} onExit={()=>{setPage('home');void refresh();}} onError={setError}/>}
 {page==='library'&&<div className="page-content"><div className="page-heading"><h1>내 영상</h1><p>영상이 바뀌어도 지금까지의 연습은 이어집니다.</p></div>{linkForm}<div className="library-list">{state.sources.map(s=><SourceRow key={s.id} source={s} active={state.active?.sourceId===s.id} onSelect={async()=>{await api('/sources/'+s.id+'/select',{});await refresh();setToast('다음 연습의 주 영상으로 선택했어요.');}}/>)}</div><div className="info-box"><CircleHelp size={20}/><p>영상 자막은 틀릴 수 있어요. 음성과 대조하지 않은 구간은 자유 청취로 제공하며, 이해도를 확정 채점하지 않습니다. 준비가 안 되는 동안에도 기본 연습을 이어갈 수 있어요.</p></div><button className="primary-button" onClick={()=>void start()}>연습 시작 <Play size={17}/></button><section className="recommendations"><div className="section-heading"><h2>다음에 살펴볼 자료</h2><span>{state.recommendationCheck?.status==="checking"?"공식 자료 확인 중":"앱 사용 시 주간 확인"}</span></div>{state.recommendations.length?state.recommendations.map(r=><article key={r.id}><div><h3>{r.title}</h3><p>{r.reason}</p><small>{date(r.checkedAt)} 확인 · {r.available?"페이지 접근 확인":"현재 접근 확인 안 됨"}{r.type==="site"?" · 외부 학습 사이트":" · 자막은 추가 시 확인"}</small></div><a className="text-link" href={r.url} target="_blank" rel="noreferrer">자료 보기 <ExternalLink size={14}/></a></article>):<p className="muted">기술 설명과 관련 있는 공식 학습 자료를 확인하고 있어요.</p>}</section></div>}
 {page==='history'&&<div className="page-content"><div className="page-heading"><h1>조금씩, 쌓이는 이해.</h1><p>연습한 문장의 익숙함과 새 문장의 이해를 나누어 기록합니다.</p></div><div className="skill-table">{summary.skills.map(s=><div key={s.id}><span>{s.label}<small>{s.state}</small></span><span>{s.fresh?`${s.correct} / ${s.fresh}`:'아직 기록 없음'}<small>도움 없이 답한 앱 내 새 문장</small></span></div>)}</div><h2 className="section-title">최근 연습 노트</h2>{!summary.attempts.length?<div className="empty"><BookOpen size={30}/><h3>첫 기록을 만들어 보세요.</h3><p>반복 횟수와 도움이 필요했던 순간도 함께 남습니다.</p><button className="primary-button" onClick={()=>void start()}>연습 시작</button></div>:<div className="timeline">{summary.attempts.map((a,i)=><article key={i}><span className="timeline-dot"/><div><small>{date(a.at)} · {state.goals[a.goal]}</small><h3>{!a.scored?'영상 자유 청취':a.correct?'의미를 이해했어요':'다음 사례에서 다시 연결해요'}</h3><p>{a.scored?(a.helped?'도움을 사용한 응답':a.firstExposure?'앱에서 처음 연습한 문장':'다시 만난 문장'):'자기 점검 기록 · 확정 점수에 포함하지 않음'} · 재생 {a.plays}회</p>{a.note&&<blockquote>{a.note}</blockquote>}</div></article>)}</div>}</div>}
 {page==='baseline'&&<div className="page-content"><div className="page-heading"><h1>나의 출발점</h1><p>한 달 뒤의 나와 비교할 수 있도록 처음의 반응을 남겼어요.</p></div><div className="baseline-paper"><span className="date-tag">{summary.baseline.date}</span><h2>{summary.baseline.summary}</h2>{summary.baseline.observations.map((o,i)=><p key={o}><span>{i+1}</span>{o}</p>)}<div className="info-box"><CircleHelp size={18}/><p>{summary.baseline.note}</p></div><footer>다음 비교 예정일 <b>{summary.baseline.reviewDate}</b><small>새로운 비슷한 난도의 발화로 짧게 확인합니다. 자동 알림은 설정되어 있지 않습니다.</small></footer></div></div>}
 {page==='settings'&&<div className="page-content"><div className="page-heading"><h1>학습을 이어가는 설정</h1><p>기록은 이 컴퓨터의 데이터베이스에 저장됩니다.</p></div><section className="settings-section"><h2>백업과 복원</h2><p>답변, 복습 일정, 영상과 출발점 기록을 함께 보관하세요.<br/>다른 컴퓨터로 옮길 때 백업 파일을 가져오면 됩니다.</p><div className="button-row"><a className="primary-button" href="/api/backup" download><Download size={17}/> 백업 내보내기</a><label className="secondary-button"><Upload size={17}/> 백업 가져오기<input type="file" accept=".json" hidden onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;const d=JSON.parse(await f.text());const result=await api('/restore',d);await refresh();setToast(`${result.count}개 항목을 확인했어요. 기존 기록은 유지됩니다.`);}catch(x){setError((x as Error).message);}e.target.value='';}}/></label></div></section><section className="settings-section"><h2>음성과 AI 도움</h2><p>기본 연습은 기기의 영어 합성 음성을 사용합니다. 실제 화자의 억양 학습과는 구분됩니다.</p><p>영상의 한국어 AI 설명: <b>{state.ai.configured?state.ai.model:'아직 연결하지 않음'}</b></p><p className="muted">로컬 Ollama 모델을 실행하고 LISTENING_AI_MODEL을 지정하면 설명을 사용할 수 있습니다. 연결 전에도 영어 자막 확인과 기본 연습이 가능합니다.</p></section><section className="settings-section"><h2>기록을 해석하는 방법</h2><p>앱 밖에서 본 영상은 자동으로 알 수 없습니다. 익숙한 구간은 연습 중 ‘이미 익숙해요’로 알려주세요. 자막 오류 신고와 건너뛰기는 오답으로 계산하지 않습니다.</p></section></div>}
 </main>{toast&&<div className="toast" role="status"><CheckCircle2 size={19}/>{toast}</div>}</div>;
}

function SourceRow({source:s,active,onSelect}:{source:Source;active:boolean;onSelect:()=>Promise<void>}){
 const [err,setErr]=useState('');return <article className="source-row"><div className="source-thumb"><img src={`https://i.ytimg.com/vi/${s.id}/mqdefault.jpg`} alt="" loading="lazy"/><span><Play size={17} fill="currentColor"/></span></div><div className="source-copy"><div className="source-meta">{active&&<span className="pill">학습 중</span>}<span>{s.count||0}개 구간</span></div><h3>{s.title}</h3><p>{s.message}</p>{err&&<p className="inline-error">{err}</p>}</div><button className="source-select" aria-label={`${s.title} 선택`} onClick={()=>void onSelect().catch(x=>setErr(x.message))}>{s.status==='fetching'||s.status==='queued'?<LoaderCircle className="spin" size={20}/>:<ChevronRight size={21}/>}</button></article>;
}

function Practice({initial,onDone,onExit,onError}:{initial:Bundle;onDone:()=>Promise<void>;onExit:()=>void;onError:(s:string)=>void}){
 const [b,setB]=useState(initial);const [played,setPlayed]=useState(false);const [showText,setShowText]=useState(false);const [meaning,setMeaning]=useState('');const [aiNote,setAiNote]=useState(false);const [answer,setAnswer]=useState<number|null>(null);const [reflection,setReflection]=useState<string|null>(null);const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [extra,setExtra]=useState('');
 const e=b.exercises[b.session.index];const a=e?b.attempts.find(x=>x.exerciseId===e.id):undefined;
 useEffect(()=>{if(!e)return;setPlayed(b.events.some(x=>x.exerciseId===e.id&&['played','external_listen'].includes(x.type)));setShowText(false);setMeaning('');setAnswer(null);setReflection(null);setNote('');setExtra('');},[e?.id]);
 async function ev(type:string,value?:unknown){if(!e)return;await api('/events',{id:crypto.randomUUID(),sessionId:b.session.id,exerciseId:e.id,type,value});if(type==='played'||type==='external_listen')setPlayed(true);}
 async function check(){setBusy(true);try{const at=await api<Attempt>('/attempts',{sessionId:b.session.id,exerciseId:e.id,answer,reflection,note});setB({...b,attempts:[...b.attempts,at]});await ev('feedback');}catch(x){onError((x as Error).message);}finally{setBusy(false);}}
 async function next(skip=false){setBusy(true);try{await api('/sessions/'+b.session.id+'/next',{index:b.session.index,skip});setB(await api<Bundle>('/sessions/'+b.session.id));}catch(x){onError((x as Error).message);}finally{setBusy(false);}}
 if(!e||b.session.status==='completed')return <div className="session-complete"><span className="complete-mark"><Check size={40}/></span><h1>오늘의 연습을 남겼어요.</h1><p>{b.attempts.length}개 응답과 도움을 받은 순간을 저장했습니다.<br/>다음에는 같은 구조의 다른 문장으로 이어가요.</p><div className="button-row"><button className="primary-button" onClick={()=>void onDone()}>학습 기록 보기 <ArrowRight size={17}/></button><button className="secondary-button" onClick={onExit}>오늘은 여기까지</button></div></div>;
 return <div className="practice-wrap"><div className="practice-header"><button className="plain-button" onClick={onExit}><X size={18}/> 저장하고 나가기</button><span>{b.session.index+1} / {b.exercises.length}</span></div><div className="progress-track"><i style={{width:`${(b.session.index+1)/b.exercises.length*100}%`}}/></div><div className="exercise-heading"><span>{e.kind==='speech'?'짧은 문장 연습':'영상으로 돌아가기'}</span><h1>{a?'이제 소리와 뜻을 연결해 보세요.':'먼저 듣고, 의미를 잡아보세요.'}</h1><p>{e.kind==='speech'?'모든 단어를 적을 필요는 없어요. 설명의 뜻에 집중해 보세요.':'영어 자막은 필요할 때만 열어보세요. 이 구간은 자기 점검으로 기록합니다.'}</p></div>
 <Player key={e.id} exercise={e} onEvent={ev}/><div className="help-row"><button className="plain-button" onClick={async()=>{try{if(!showText)await ev('transcript');setShowText(!showText);}catch(x){onError((x as Error).message);}}}><BookOpen size={16}/>{showText?'영어 문장 접기':'영어 문장 보기'}</button><button className="plain-button" onClick={async()=>{try{await ev('familiar');setExtra('익숙한 구간으로 기록했어요. 새 발화 성과와 구분합니다.');}catch(x){onError((x as Error).message);}}}><Check size={16}/> 이미 익숙해요</button></div>
 {showText&&<div className="transcript"><p lang="en">{e.text}</p><small>{e.kind==='youtube'?'수집된 자막 · 음성과 다를 수 있습니다.':e.pattern}</small></div>}
 {!a?<section className="answer-section"><h2>{e.prompt}</h2>{e.options.length?<div className="answers">{e.options.map((o,i)=><button key={o} className={answer===i?'selected':''} disabled={!played} onClick={()=>setAnswer(i)}><span>{String.fromCharCode(65+i)}</span>{o}{answer===i&&<Check size={17}/>}</button>)}<button className={'unsure '+(answer===-1?'selected':'')} disabled={!played} onClick={()=>setAnswer(-1)}>모르겠어요</button></div>:<><div className="reflection-buttons">{[['understood','핵심이 이해돼요'],['partial','일부만 들려요'],['lost','연결하기 어려워요']].map(([id,label])=><button disabled={!played} className={reflection===id?'selected':''} onClick={()=>setReflection(id)} key={id}>{label}</button>)}</div><textarea aria-label="들린 내용 메모" placeholder="들린 표현이나 이해한 내용 (선택)" value={note} onChange={x=>setNote(x.target.value)}/></>}
 <div className="answer-actions"><button className="plain-button" disabled={busy} onClick={()=>void next(true)}>다른 문장으로</button><button className="primary-button" disabled={busy||!played||(e.options.length?answer===null:!reflection)} onClick={()=>void check()}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>} {e.options.length?'의미 확인':'기록하기'}</button></div></section>:<section className="feedback"><div className="feedback-title">{a.correct?<CheckCircle2 size={23}/>:<BookOpen size={23}/>}<h2>{a.scored?(a.correct?'의미를 잘 잡았어요.':'이 부분을 연결해 보세요.'):'지금 들린 정도를 기록했어요.'}</h2></div><p>{e.explanation||'같은 설명을 다시 듣거나, 영어 문구를 확인한 뒤 소리와 연결해 보세요.'}</p>{e.meaning&&<p className="meaning">{e.meaning}</p>}<div className="button-row"><button className="secondary-button" onClick={async()=>{try{await ev('transcript');setShowText(true);}catch(x){onError((x as Error).message);}}}><BookOpen size={16}/> 영어 문구 확인</button>{!e.meaning&&<button className="secondary-button" disabled={busy} onClick={async()=>{setBusy(true);try{await ev('meaning');const r=await api('/exercises/'+encodeURIComponent(e.id)+'/explain',{});setMeaning(r.meaning+' '+r.explanation);setAiNote(r.ai);}catch(x){onError((x as Error).message);}finally{setBusy(false);}}}>한국어 설명</button>}<button className="primary-button" disabled={busy} onClick={()=>void next()}>다음 문장 <ArrowRight size={17}/></button></div>{meaning&&<div className="meaning"><p>{meaning}</p>{aiNote&&<small>AI 설명 · 원문과 다를 수 있어요.</small>}</div>}</section>}
 <div className="exercise-footer"><button className="plain-button" onClick={async()=>{try{await ev('content_issue');setExtra('문항 문제로 기록했어요. 다음 문장으로 넘어가도 괜찮아요.');}catch(x){onError((x as Error).message);}}}><Flag size={14}/> 답이나 자막이 이상해요</button><small>응답은 자동으로 저장됩니다.</small></div>{extra&&<p className="inline-notice" role="status">{extra}</p>}</div>;
}

createRoot(document.getElementById('root')!).render(<App/>);
